name: "Build Packages"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@55718cd9ebf1737a061487d5ada21abf31e99a98

      - name: Build packages and copy to archive
        run: |
          mkdir -p nix-archive

          nix build .#nixosConfigurations.laptop.config.system.build.toplevel
          nix copy --to file://$PWD/nix-archive $(readlink result)

      - uses: actions/upload-artifact@v7
        with:
          name: nix-packages
          path: ./nix-archive

