name: "Build Packages"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/magic-nix-cache-action@03659f4394aec2317771e29041ef266669e2ee12

      - run: |
          mkdir -p nix-archive

          nix build .#plasma-final
          nix copy --to file://$PWD/nix-archive $(readlink result)
          nix build .#plasma-prev
          nix copy --to file://$PWD/nix-archive $(readlink result)

      - uses: actions/upload-artifact@v7
        with:
          name: nix-packages
          path: ./nix-archive

